module.exports = {
  docs: [
    { type: "doc", id: "start" },
    {
      type: "category",
      label: "hooks",
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "hooks" }],
    },
  ],
};
